"""Explicit candidate provisioning; normal application startup only verifies.

The schema is generated by the existing SQLite migrations in memory. Remote
SQL is inspected as data, never executed on the local machine. Existing
incompatible databases are refused rather than repaired or overwritten.
"""
from __future__ import annotations

import re
import sqlite3
from functools import lru_cache

VERSION_DDL = """CREATE TABLE _schema_version (
  singleton INTEGER PRIMARY KEY CHECK(singleton = 1),
  version INTEGER NOT NULL
)"""


def _normalize_ddl(sql: str) -> str:
    # Preserve string literals and quoted identifiers exactly.
    parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\")", sql.strip().rstrip(";"))
    return "".join(re.sub(r"\s+", " ", part) if i % 2 == 0 else part
                   for i, part in enumerate(parts))


def _objects(conn) -> dict[tuple[str, str], str]:
    return {(row[0], row[1]): row[2] for row in conn.execute(
        "SELECT type,name,sql FROM sqlite_master "
        "WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
        "ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END,name"
    )}


@lru_cache(maxsize=1)
def expected_objects() -> dict[tuple[str, str], str]:
    from database import db

    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA foreign_keys=ON")
        for statement in db.SCHEMA.split(";"):
            if statement.strip():
                conn.execute(statement)
        db._migrate(conn)
        return _objects(conn)
    finally:
        conn.close()


def _verify_objects(actual: dict, expected: dict) -> None:
    if any(key not in actual or _normalize_ddl(actual[key]) != _normalize_ddl(sql)
           for key, sql in expected.items()):
        raise sqlite3.DatabaseError("Turso schema differs from the supported V8 contract")
    # Additional triggers on ledger tables could change write semantics. Extra
    # operational tables are allowed; application schema changes require review.
    for key in actual:
        if key[0] == "trigger" and key not in expected:
            raise sqlite3.DatabaseError("Turso schema contains an unrecognized trigger")


def _version(conn) -> int:
    rows = conn.execute("SELECT singleton,version FROM _schema_version").fetchall()
    if len(rows) != 1 or rows[0][0] != 1 or type(rows[0][1]) is not int:
        raise sqlite3.DatabaseError("Invalid Turso schema version metadata")
    return rows[0][1]


def verify_schema(conn) -> None:
    from database import db

    actual = _objects(conn)
    version_sql = actual.get(("table", "_schema_version"))
    if version_sql is None:
        raise sqlite3.DatabaseError("Turso candidate must be initialized explicitly before startup")
    if _normalize_ddl(version_sql) != _normalize_ddl(VERSION_DDL):
        raise sqlite3.DatabaseError("Invalid Turso schema version table")
    if _version(conn) != db.V8_SCHEMA_VERSION:
        raise sqlite3.DatabaseError("Unsupported Turso schema version; migration required")
    _verify_objects(actual, expected_objects())


def initialize_candidate(conn) -> dict:
    """Create an empty candidate or adopt an exact V8 import, atomically.

    Caller must select a disposable candidate explicitly. No application rows
    are modified. Existing versions or incompatible schema are never repaired.
    """
    from database import db

    actual = _objects(conn)
    expected = expected_objects()
    if ("table", "_schema_version") in actual:
        verify_schema(conn)
        return {"initialized": True, "changed": False, "schema_version": db.V8_SCHEMA_VERSION}
    # A database used solely by the separate persistence probe is still empty
    # of application data, but arbitrary preexisting tables are not.
    app_objects = {key: sql for key, sql in actual.items()
                   if not key[1].startswith("turso_candidate_probe")}
    if app_objects:
        if conn.execute("PRAGMA user_version").fetchone()[0] > db.V8_SCHEMA_VERSION:
            raise sqlite3.DatabaseError("Imported database schema is newer than supported")
        _verify_objects(app_objects, expected)
        statements = []
    else:
        statements = [(sql, ()) for sql in expected.values()]
    statements += [
        (VERSION_DDL, ()),
        ("INSERT INTO _schema_version(singleton,version) VALUES(1,?)", (db.V8_SCHEMA_VERSION,)),
    ]
    if hasattr(conn, "execute_batch"):
        conn.execute_batch(statements, atomic=True)
    else:
        conn.execute("BEGIN IMMEDIATE")
        try:
            for sql, args in statements:
                conn.execute(sql, args)
            conn.commit()
        except Exception:
            conn.rollback()
            raise
    verify_schema(conn)
    return {"initialized": True, "changed": True, "schema_version": db.V8_SCHEMA_VERSION}
